### PR TITLE
fix posix name

### PR DESCRIPTION
**Pull request by agaricus**

### CODE REVIEW

**Comment by guigrpa** [comment]
You're totally right, but the change should be in package.coffee (at the root of the repo), at the end. The manifest.json file is generated programmatically.

**Comment by agaricus** [comment]
I'm guessing not - should rename resources=(

**Comment by guigrpa** [comment]
Please revert commit #39f84ae and I can merge this PR

**Comment by guigrpa** [comment]
Rationale: It will be regenerated the next time the Chrome extension is published

**Comment by agaricus** [comment]
done. thanks

**Pull request merged**
